"use client";
import {useEffect,useState} from "react";
import {ArrowUpRight,ArrowLeft,ArrowRight,Sparkles,Lightbulb,Flag,Vote,Pause,Play} from "lucide-react";
import {useMarket} from "@/lib/use-market";
import {EventHeader,SampleNotice,sampleIds} from "./event-ui";
import "./event-design.css";
import "./play/play.css";
const entries=[{title:"破冰",subtitle:"一句开场，认识一个新搭子",href:"/join#icebreak",action:"抽一张任务卡",icon:Sparkles,tone:"coral"},{title:"求助",subtitle:"把卡点说出来，让现场一起回应",href:"/join#help",action:"发布 / 回应求助",icon:Lightbulb,tone:"blue"},{title:"进展",subtitle:"第一次跑通，也值得被全场看见",href:"/join#progress",action:"分享一次小胜利",icon:Flag,tone:"green"},{title:"投票",subtitle:"支持一个你想继续了解的好点子",href:"/vote",action:"看看作品 · 投票",icon:Vote,tone:"lilac"}];
const stages=[{title:"先让对话发生",text:"在手机端抽一张破冰任务。认识新搭子后，点“我完成了”，服务器确认后才会同步到大屏。",href:"/join#icebreak",action:"试试破冰抽卡"},{title:"接住一个现场信号",text:"发布求助，或者回应一个你能解决的问题。原有发布、认领、解决权限保留，让帮忙走到最后一步。",href:"/join#help",action:"去求助广场"},{title:"让好点子被看见",text:"分享进展、了解作品、投出支持。正式投票由服务器确认；本机演示独立，不会增加现场票数。",href:"/vote",action:"看看作品与投票"}];
export default function Home(){const{market,error}=useMarket();const[step,setStep]=useState(0);const[playing,setPlaying]=useState(false);const[reduce,setReduce]=useState(true);const[project,setProject]=useState("");
useEffect(()=>{const q=window.matchMedia("(prefers-reduced-motion: reduce)");const changed=()=>setReduce(q.matches);changed();q.addEventListener("change",changed);return()=>q.removeEventListener("change",changed);},[]);
useEffect(()=>{if(!playing||reduce)return;const timer=setInterval(()=>setStep(v=>(v+1)%3),6500);return()=>clearInterval(timer);},[playing,reduce]);
useEffect(()=>{if(!project)return;const previous=document.activeElement as HTMLElement|null;const dialog=document.querySelector<HTMLElement>('.project-dialog');const focusables=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href]')||[]);focusables()[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setProject('');if(e.key==='Tab'){const fs=focusables(),first=fs[0],last=fs[fs.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[project]);
const events=(market?.events||[]).filter(e=>!e.demo&&e.status!=="hidden");const votes=events.filter(e=>e.kind==="vote"&&e.status==="open");const helps=events.filter(e=>e.kind==="help"&&(e.status==="open"||e.status==="claimed"));const shown=market?.teams.find(t=>t.id===project);const stage=stages[step];
return <main className="event-page"><EventHeader/><section className="menti-hero"><p className="hero-kicker">未央 / HACKATHON LIVE</p><h1>让每个想法，<br/>都有人<span>回应。</span></h1><p className="hero-intro">让埋头创作的我们，也能抬头遇见彼此。<br/>从一次破冰、一句求助，到一个值得被看见的作品。</p><SampleNotice teams={market?.teams||[]}/><div className="interaction-rows">{entries.map(e=><div className="interaction-row" key={e.title}><div className={`feature-glyph ${e.tone}`}><e.icon size={34}/></div><h2>{e.title}</h2><p>{e.subtitle}</p><a href={e.href} className="pill-action">{e.action}<ArrowUpRight size={19}/></a></div>)}</div><div className="play-invite"><div>30 秒，认识一个新搭子。<span>按钮接力，也能完成一轮。</span></div><a href="/play">试试声浪接力 ↗</a></div><p className="connection-status" role="status">{error?"现场连接暂时中断，正在重试。":market?`${market.teams.length} 支队伍（含示例） · ${market?.totalVotes||0} 票服务器已确认支持 · ${helps.length} 个求助待回应`:"正在连接现场数据…"}</p></section>
<section className="steps-section"><div className="section-heading"><h2>从一个问题，<br/><span>到一次回应。</span></h2><p>手机负责参与。大屏负责让所有人看见。</p></div><div className="steps-layout"><div className="step-list">{stages.map((s,i)=><button className={step===i?"active":""} aria-pressed={step===i} onClick={()=>{setStep(i);setPlaying(false);}} key={s.title}><span className="step-number">0{i+1}</span><div><h3>{s.title}</h3><p>{s.text}</p></div></button>)}</div><section className="step-demo" aria-live="polite"><div className="demo-toolbar"><span>参与端 ↔ 现场大屏</span><b>0{step+1} / 03</b></div><div className="demo-content" key={step}><small>当前环节 / {stage.title}</small>{step===0?<><h3>今晚，你想认识<br/>怎样的新搭子？</h3><div className="question-card"><Sparkles/><p>找一位与你技术栈不同的人，<br/>互相介绍正在做的点子。</p><span>示例任务 · 完成操作在参与端</span></div></>:step===1?<><h3>一条求助，<br/>也许刚好有人会。</h3><div className="question-card"><Lightbulb/><p>{helps[0]?.note||"还没有待处理的真实求助。你可以成为第一个发出信号的人。"}</p><span>{helps[0]?"服务器现场数据":"当前现场状态"}</span></div></>:<><h3>你的支持，<br/>有一个明确的去处。</h3><div className="demo-votes">{market?.teams.slice(0,3).map(t=>{const count=market?.voteCounts?.[t.id]||0;return <div key={t.id}><span>{t.name}{sampleIds.has(t.id)&&" · 示例"}</span><b>{count} 票</b><i style={{width:`${market?.totalVotes?count/market.totalVotes*100:0}%`}}/></div>;})}</div></>}<a className="pill-action" href={stage.href}>{stage.action}<ArrowUpRight size={18}/></a></div><div className="demo-controls"><button aria-label="上一个环节" onClick={()=>{setPlaying(false);setStep(v=>(v+2)%3);}}><ArrowLeft size={18}/></button><button aria-label={playing?"暂停环节演示":"播放环节演示"} disabled={reduce} onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={18}/>:<Play size={18}/>}{reduce?"减动效模式":playing?"暂停":"播放"}</button><button aria-label="下一个环节" onClick={()=>{setPlaying(false);setStep(v=>(v+1)%3);}}><ArrowRight size={18}/></button></div></section></div></section>
<section className="works-section"><div className="section-heading"><h2>今晚的作品，<br/>和创造它们的人。</h2><p>先了解，再支持。每一个项目都值得一次认真观看。</p></div><div className="project-grid">{market?.teams.map((t,i)=><article className="project-card" key={t.id}><button className={`project-art art-${i%4}`} aria-label={`查看${t.name}作品详情`} onClick={()=>setProject(t.id)}><span>{t.code.slice(0,3)}</span><div className="paper-symbol">{i%3===0?<Sparkles size={70}/>:i%3===1?<Lightbulb size={70}/>:<Flag size={70}/>}</div><small>{sampleIds.has(t.id)?"示例作品 / 非真实参赛队":"现场登记作品"}</small></button><div className="project-copy"><small>{sampleIds.has(t.id)?"EXAMPLE PROJECT":"LIVE PROJECT"}</small><h3>{t.name}</h3><p>{t.idea}</p><button className="text-link" onClick={()=>setProject(t.id)}>了解作品 <ArrowUpRight size={18}/></button></div></article>)}</div>{!market?.teams.length&&<div className="event-empty">{error||"等待队伍登记作品。"}<a href="/join">登记你的队伍 ↗</a></div>}</section>
<section className="final-call"><h2>别让好点子，<br/><span>只留在你的屏幕里。</span></h2><a className="pill-action" href="/join">现在加入现场<ArrowUpRight size={19}/></a><a className="text-link" href="/screen">打开现场大屏 ↗</a></section><footer className="event-footer"><span>未央 · WEYOUNG PULSE</span><p>一次对话，一次回应，一起完成。</p><a href="/join">参与现场 ↗</a></footer>
{shown&&<div className="project-dialog-backdrop" onClick={()=>setProject("")}><section className="project-dialog" role="dialog" aria-modal="true" aria-labelledby="project-dialog-title" onClick={e=>e.stopPropagation()}><button className="dialog-close" aria-label="关闭作品详情" onClick={()=>setProject("")}>×</button><small>{sampleIds.has(shown.id)?"示例作品 / 不代表真实参赛名单":"现场登记作品"}</small><h2 id="project-dialog-title">{shown.name}</h2><p>{shown.idea}</p><div className="project-status"><b>现场进展</b><p>{events.find(e=>e.teamId===shown.id&&e.kind==="milestone")?.label||"尚未发布真实进展"}</p></div><a className="pill-action" href={`/vote?team=${encodeURIComponent(shown.id)}`}>去投票页了解并确认<ArrowUpRight size={18}/></a><div className="dialog-switch"><button onClick={()=>{const ts=market?.teams||[];const i=ts.findIndex(t=>t.id===shown.id);setProject(ts[(i+ts.length-1)%ts.length]?.id||"");}}>← 上一个作品</button><button onClick={()=>{const ts=market?.teams||[];const i=ts.findIndex(t=>t.id===shown.id);setProject(ts[(i+1)%ts.length]?.id||"");}}>下一个作品 →</button></div></section></div>}</main>;}
